export const LOAD_CREW_REQUEST = 'LOAD_CREW_REQUEST';
export const LOAD_CREW_SUCCESS = 'LOAD_CREW_SUCCESS';
export const LOAD_CREW_FAILURE = 'LOAD_CREW_FAILURE';

export const MOVE_CREW_FORWARD = 'MOVE_CREW_FORWARD';
export const MOVE_CREW_BACKWARD = 'MOVE_CREW_BACKWARD';

export const FILTER_CREW = 'FILTER_CREW';
